services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "9000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    working_dir: /home/dynamodblocal
    env_file:
      - .env
    deploy:
      labels:
        com.docker.compose.container-name: "dynamodb-local"
